[project]
name = "ai-dungeon-master-bot"
version = "0.1.0"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "aiofiles==24.1.0",
    "aiogram==3.22.0",
    "groq>=1.0.0",
    "python-dotenv==1.2.1",
    "requests==2.32.5",
]

[dependency-groups]
dev = [
    "ruff>=0.14.13",
]
